name: Update Lambda Function

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      - name: Update Lambda function
        uses: aws-actions/aws-lambda@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AMPLIFY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AMPLIFY_SECRET_ACCESS_KEY }}
          region: 'us-east-2'
          function-name: 'iotsensordatac61c9330-iotsensor'
          zip-file: showData.zip
